### ISSUE TITLE
Doesn't compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by DraTeots** [fmtlib/format-benchmark#9]
Hi!

Compiling the project on ubuntu gives me:
```
Scanning dependencies of target cxx03_test
[ 70%] Building CXX object benchmark/test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o
/home/romanov/test_lab/format-benchmark/benchmark/test/cxx03_test.cc:8:2: error: #error C++11 or greater detected. Should be C++03.
 #error C++11 or greater detected. Should be C++03.
  ^~~~~
make[2]: *** [benchmark/test/CMakeFiles/cxx03_test.dir/build.make:63: benchmark/test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1199: benchmark/test/CMakeFiles/cxx03_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

gcc version ```gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0```
clang verstion ```clang version 7.0.0-3```
